export const ACTIONS = {
    SET_USER: "SET_USER",
    ADD_TO_BASKET: 'ADD_TO_BASKET',
    REMOVE_FROM_BASKET: 'REMOVE_FROM_BASKET',
    INCREASE_PRODUCT: 'INCREASE_PRODUCT',
    DECREASE_PRODUCT: 'DECREASE_PRODUCT',
    INCREASE_BASKET: 'INCREASE_BASKET',
    DECREASE_BASKET: 'DECREASE_BASKET'
}